server.port: 9092


spring.data.mongodb.uri=mongodb://10.7.93.19:27017/onboarding
#spring.data.mongodb.uri=mongodb://localhost:27017/onboarding
email.regex: [A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$
mobile.regex: 01[0-9]{9}$
valid-password.regex: ^(?=.*[A-Z])(?=.*[a-z])(?=.*[@_])(?=.*\\d)[A-Za-z\\d@_]{6,}$

frontEndUrl: http://10.20.242.202:3000,http://localhost:3000,http://localhost:5175

keycloak.url: http://10.7.93.19:8090
keycloak.tokenUrl: /realms/bracepl-dbp/protocol/openid-connect/token
keycloak.realm: bracepl-dbp
keycloak.clientId: auth-service
keycloak.clientSecret: exUb7Sar4wubSvIGoGuVYHkiqg3r4i8p
keycloak.admin.username: admin
keycloak.admin.password: admin

notificationService.baseUrl: http://10.7.93.19:8081/
notificationService.sendOtp: otp/send
notificationService.otpValidate: otp/validate
notificationService.endpoint: otp/endpoint
notificationService.send-email: notification/email
notificationService.send-sms: notification/sms

ekyc.service.endpoint: http://10.7.93.19:8083/api/extract-text

nidVerification.baseUrl: https://ekycboolean.reliefvalidation.com.bd
nidVerification.apiKey: I3JlbGllZi12YWxpZGF0aW9uLWxpbWl0dGVkLTIwMjUtYmFuZ2xhZGVzaC1ndWxzaGFuLTEtZGhha2EtMzItcm9hZC1yYW5jb24tYnVpbGRpbmctYnJhYy1lcGwtMjAyNS0wNC0zMA==
nidVerification.origin: http://103.30.61.14
nidVerification.verification: /api/verification

nidVerification.dir: /uploads

investor-code.dir: ""
investor-code.prefix: ""
