#spring.application.name=dbp-onboarding-service
##upload.dir=src/main/resources/uploads/
#upload.dir=uploads/
#investor-code.dir=src/main/resources/uploads/investor-codes.txt
#investor-code.prefix=BESL
#spring.servlet.multipart.max-file-size=20MB
#spring.servlet.multipart.max-request-size=20MB
#
##logging.file.name=
#
##logging.config=classpath:logback-spring.xml
#
#
##spring.data.mongodb.uri=mongodb://10.7.93.19:27017/onboarding
#spring.data.mongodb.uri=mongodb://localhost:27017/Onboarding
#reset-password-url = resetPasswordUrl;
#
#logging.level.org.springframework.security=DEBUG
#frontEndUrl=http://10.20.242.202:3001,http://localhost:5174,http://localhost:5175,http://10.20.242.202:5174,https://bbuat.bracepltrade.com,https://bb.bracepltrade.com/
#
#
##ekyc.service.endpoint = http://10.20.242.95:8081/api/extract-text
#ekyc.service.endpoint = http://10.7.93.19:8083/api/extract-text
##notification-service.baseUrl = http://10.20.242.239:8081/
#notification-service.baseUrl = http://10.7.93.19:8081/
#notification-service.sendOtp = otp/send
#notification-service.otpValidate = otp/validate
#notification-service.endpoint = otp/endpoint
#notification-service.send-email = notification/email
#notification-service.send-sms = notification/sms
#
#email.regex = [A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$
#mobile.regex = 01[0-9]{9}$
#valid-password.regex = ^(?=.*[A-Z])(?=.*[a-z])(?=.*[@_])(?=.*\\d)[A-Za-z\\d@_]{6,}$
#
#
#
#
#sms.msg.newUser = Dear User, your UserName is username and your Password is password.
#email.msg.newUser = Dear User, your UserName is username and your Password is password.
#
#nidVerification.baseUrl = https://ekycboolean.reliefvalidation.com.bd
#nidVerification.origin = http://103.30.61.14
#nidVerification.apiKey = I3JlbGllZi12YWxpZGF0aW9uLWxpbWl0dGVkLTIwMjUtYmFuZ2xhZGVzaC1ndWxzaGFuLTEtZGhha2EtMzItcm9hZC1yYW5jb24tYnVpbGRpbmctYnJhYy1lcGwtMjAyNS0wNC0zMA==
#nidVerification.verification = /api/verification
#
keycloak.url=http://10.7.93.19:8090
keycloak.realm=bracepl-dbp
keycloak.admin.username=admin
keycloak.admin.password=admin

server.port:9092
